# 1. How to build/install the project
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

# 2. Basic identity
[project]
name = "prospector-emulator-libs"
version = "0.0.1"

# 3. Tell setuptools which Python package belongs to this project
[tool.setuptools.packages.find]
where = ["."]
include = ["prospector_emulator_libs*"]
