Data:
  train_data: random_samples/train/train_x_coef_mfrac_100k.h5
  valid_split: 0.1                 # this will be ignored if valid_data is not empty
  valid_split_seed: 42
  valid_data: random_samples/valid/valid_x_coef_mfrac_flux_10k.h5
  test_data: random_samples/test/test_x_coef_mfrac_flux_10k.h5

Device: auto

Scaler:
  flux_scaling: log10_standard                    # none, standard, global_standard, log10_none, log10_standard, log10_global_standard
  mfrac_scaling: standard               # none, standard

DataLoader:
  train_batch_size: 1000
  valid_batch_size: 1000
  train_num_workers: 4
  # train_persistent_workers: 2
  train_shuffle: True
  valid_shuffle: True

  test_batch_size: 2000
  test_num_workers: 2
  # test_persistent_workers: 2
  test_shuffle: True

Emulator:
  shared_dims: [1024, 1024, 1024, 1024]
  flux_head_dims: 
  mfrac_head_dims: 
  activation: gelu                      # gelu, relu, silu, elu, tanh, leaky_relu
  dropout: 0.0
  predict_mfrac: True

Loss:
  flux_loss: mae                        # mse, mae
  flux_loss_space: scaled               # scaled, log10, linear
  mfrac_loss: mae                       # mse, mae
  mfrac_lambda: 0.0001
  max_log10_flux:
  wavelength_weights:

Optimizer:
  name: adam                            # adam, adamw, sgd, rmsprop
  learning_rate: 1.0E-3
  weight_decay: 0.0

Training:
  # device: auto
  max_epochs: 800
  patience: 50
  abs_tol: 0.0
  rel_tol: 0.001
  monitor: total                        # total, coef, mfrac
  verbose: True

Outputs:
  outputs_dir: flux_emulator_outputs
  save_plots: True
  # plot_dir: 
  save_emulator: True
  # emulator_dir: 
  emulator_filename: flux_emulator.pt
